"""Vision test (images / OCR) against the local server. Standard library only.

Uso:
   python tools/check_vision.py                       (uses a test image generated by the script itself)
   python tools/check_vision.py foto.png              (PNG, JPG, WEBP...; any format Edge can read)
   python tools/check_vision.py foto.png "Transcribe the text" --guardar resultado.txt
"""
import argparse, base64, json, mimetypes, os, struct, sys, time, urllib.request, zlib

URL = "http://127.0.0.1:1234"
MODELO = "lfm2.5-vl-1.6b"

LETRAS = {
    "H": ["10001", "10001", "10001", "11111", "10001", "10001", "10001"],
    "O": ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
    "L": ["10000", "10000", "10000", "10000", "10000", "10000", "11111"],
    "A": ["01110", "10001", "10001", "11111", "10001", "10001", "10001"],
    "2": ["01110", "10001", "00001", "00110", "01000", "10000", "11111"],
    "0": ["01110", "10001", "10011", "10101", "11001", "10001", "01110"],
    "4": ["00010", "00110", "01010", "10010", "11111", "00010", "00010"],
    " ": ["00000"] * 7,
}


def png_de_prueba(texto="HOLA 2024", escala=12):
    filas = []
    for r in range(7):
        fila = ""
        for ch in texto:
            fila += "".join(LETRAS[ch][r]) + "0"
        filas.append(fila)
    ancho_t, alto_t = len(filas[0]) * escala, 7 * escala
    w, h = ancho_t + 80, alto_t + 80
    raw = bytearray()
    for y in range(h):
        raw.append(0)
        for x in range(w):
            tx, ty = x - 40, y - 40
            negro = 0 <= tx < ancho_t and 0 <= ty < alto_t and filas[ty // escala][tx // escala] == "1"
            raw += b"\x00\x00\x00" if negro else b"\xff\xff\xff"

    def trozo(t, d):
        c = struct.pack(">I", len(d)) + t + d
        return c + struct.pack(">I", zlib.crc32(t + d) & 0xffffffff)
    return b"\x89PNG\r\n\x1a\n" + trozo(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)) + trozo(b"IDAT", zlib.compress(bytes(raw), 9)) + trozo(b"IEND", b"")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("imagen", nargs="?")
    ap.add_argument("pregunta", nargs="?", default="Transcribe todo el texto que aparece en la imagen.")
    ap.add_argument("--modelo", default=MODELO)
    ap.add_argument("--max-tokens", type=int, default=300)
    ap.add_argument("--guardar")
    a = ap.parse_args()
    if a.imagen:
        datos = open(a.imagen, "rb").read()
        tipo = mimetypes.guess_type(a.imagen)[0] or "image/png"
        nombre = os.path.basename(a.imagen)
    else:
        datos, tipo, nombre = png_de_prueba(), "image/png", "imagen de prueba (dice: HOLA 2024)"
    b64 = base64.b64encode(datos).decode()
    cuerpo = {"model": a.modelo, "temperature": 0, "max_tokens": a.max_tokens, "messages": [{"role": "user", "content": [
        {"type": "image_url", "image_url": {"url": "data:%s;base64,%s" % (tipo, b64)}},
        {"type": "text", "text": a.pregunta}]}]}
    print("Imagen: %s (%.0f KB). Pregunta: %s" % (nombre, len(datos) / 1024, a.pregunta))
    print("La primera vez carga el modelo y el codificador de imagen; puede tardar. Mire el log de la consola del servidor para ver el tiempo por pieza.")
    req = urllib.request.Request(URL + "/v1/chat/completions", json.dumps(cuerpo).encode(), {"Content-Type": "application/json"})
    t0 = time.time()
    try:
        with urllib.request.urlopen(req, timeout=1800) as r:
            res = json.loads(r.read())
    except Exception as e:
        print("Error:", e)
        if hasattr(e, "read"):
            print(e.read().decode("utf-8", "replace"))
        return 1
    seg = time.time() - t0
    txt = res["choices"][0]["message"]["content"]
    u = res.get("usage", {})
    print("\nTiempo total: %.1f s   tokens de prompt: %s   generados: %s" % (seg, u.get("prompt_tokens"), u.get("completion_tokens")))
    d = (res.get("stats") or {}).get("diag") or {}
    if d.get("imagenes"):
        print("Codificador de imagen (s):", json.dumps(d["imagenes"]))
    print("Lotes de prompt (ms):", d.get("lotes_ms"), " modelo:", d.get("modelo_ms"), "ms")
    print("\n--- Respuesta ---\n%s\n-----------------" % txt)
    if a.guardar:
        open(a.guardar, "w", encoding="utf-8").write(txt)
        print("Guardado en", a.guardar)
    return 0


sys.exit(main())
